export const SET_CURRENT_USER = 'currentUser/SET_CURRENT_USER';
export const LOGOUT_CURRENT_USER = 'currentUser/LOGOUT_CURRENT_USER';

export const SET_FRIDGE_INGREDIENTS = 'fridge/SET_FRIDGE_INGREDIENTS';
export const GET_FRIDGE_INGREDIENTS = 'fridge/GET_FRIDGE_INGREDIENTS';
export const CLEAR_FRIDGE_INGREDIENTS = 'fridge/CLEAR_FRIDGE_INGREDIENTS';
export const DELETE_FRIDGE_INGREDIENT = 'fridge/DELETE_FRIDGE_INGREDIENT';

export const SET_RECIPE_LIST = 'recipes/SET_RECIPE_LIST';
export const SET_RECIPES_INFO = 'recipes/SET_RECIPES_INFO';
